import 'package:delivery_app/core/network/dio/authenticated_network_providers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:delivery_app/core/network/socket/stomp_client.dart';
import 'package:delivery_app/features/orders/data/datasources/delivery_tracking_remote_datasource_impl.dart';
import 'package:delivery_app/features/orders/data/datasources/delivery_tracking_socket_datasource.dart' 
    as delivery_socket_ds;
import 'package:delivery_app/features/orders/data/datasources/delivery_tracking_datasource.dart';
import 'package:delivery_app/features/orders/data/repositories/delivery_tracking_repository_impl.dart';
import 'package:delivery_app/features/orders/domain/repositories/delivery_tracking_repository.dart';
import 'package:delivery_app/features/orders/domain/entities/delivery_tracking_entity.dart';
import 'package:delivery_app/features/orders/domain/usecases/tracking_usecases.dart';
import 'package:delivery_app/features/orders/domain/usecases/get_current_delivery_usecase.dart';

/// Socket Client Provider - Di chuyển từ core về feature
final deliveryTrackingStompClientProvider = Provider<StompSocketClient>((ref) {
  const url = 'ws://localhost:8085/ws/delivery-native';
  return StompSocketClient(url, name: 'DeliveryTracking');
});

/// DataSource Provider - Di chuyển từ core về feature
final deliveryTrackingSocketDataSourceProvider = Provider<DeliveryTrackingDataSource>((ref) {
  final stompClient = ref.watch(deliveryTrackingStompClientProvider);
  return delivery_socket_ds.DeliveryTrackingSocketDataSource(stompClient);
});

/// Stream provider cho entities
final deliveryTrackingStreamProvider = StreamProvider<DeliveryTrackingEntity>((ref) {
  final dataSource = ref.watch(deliveryTrackingSocketDataSourceProvider);
  return dataSource.deliveryStream;
});

/// Connection status provider
final deliveryConnectionProvider = StreamProvider<bool>((ref) {
  final dataSource = ref.watch(deliveryTrackingSocketDataSourceProvider);
  return dataSource.connectionStream;
});

/// Alias for backward compatibility
final trackingConnectionProvider = deliveryConnectionProvider;

/// Network providers
final deliveryTrackingApiServiceProvider = Provider((ref) {
  final dio = ref.watch(authenticatedDioProvider);
  return DeliveryTrackingApiService(dio);
});

final deliveryTrackingRemoteDataSourceProvider = Provider((ref) {
  final apiService = ref.watch(deliveryTrackingApiServiceProvider);
  return DeliveryTrackingRemoteDataSourceImpl(apiService);
});

/// Repository Provider - Di chuyển từ core về feature
final deliveryTrackingRepositoryProvider = Provider<DeliveryTrackingRepository>((ref) {
  final socketDataSource = ref.watch(deliveryTrackingSocketDataSourceProvider);
  final remoteDataSource = ref.watch(deliveryTrackingRemoteDataSourceProvider);
  return DeliveryTrackingRepositoryImpl(socketDataSource, remoteDataSource);
});

/// UseCase Providers
final connectDeliveryTrackingUseCaseProvider = Provider((ref) {
  final repository = ref.watch(deliveryTrackingRepositoryProvider);
  return ConnectDeliveryTrackingUseCase(repository);
});

final startDeliveryTrackingUseCaseProvider = Provider((ref) {
  final repository = ref.watch(deliveryTrackingRepositoryProvider);
  return TrackDeliveryUseCase(repository);
});

// Alias for backward compatibility
final trackDeliveryUseCaseProvider = startDeliveryTrackingUseCaseProvider;

final stopDeliveryTrackingUseCaseProvider = Provider((ref) {
  final repository = ref.watch(deliveryTrackingRepositoryProvider);
  return StopDeliveryTrackingUseCase(repository);
});

final refreshDeliveryTrackingUseCaseProvider = Provider((ref) {
  final repository = ref.watch(deliveryTrackingRepositoryProvider);
  return RefreshDeliveryTrackingUseCase(repository);
});

final getCurrentDeliveryUseCaseProvider = Provider<GetCurrentDeliveryUseCase>((ref) {
  final repository = ref.watch(deliveryTrackingRepositoryProvider);
  return GetCurrentDeliveryUseCase(repository);
});

// Since DeliveryTrackingNotifier is generated by Riverpod, we don't need manual provider
// We can just keep the following dummy one so we don't break UI components while migrating completely
final isTrackingConnectedProvider = Provider<bool>((ref) {
  return false; 
});
