import 'package:hive_flutter/hive_flutter.dart';
import '../data/dtos/cart_item_dto.dart';
import '../data/dtos/cart_dto.dart';

/// Initialize Hive and register adapters
class HiveConfig {
  static Future<void> init() async {
    // Initialize Hive Flutter
    await Hive.initFlutter();

    // Register Hive adapters (these will be generated by build_runner)
    // Hive.registerAdapter(CartItemDtoAdapter());
    // Hive.registerAdapter(CartDtoAdapter());
  }
}
