// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLdUUH8rXECtSpUnIIy-eRiTKsqz_OEdk',
    appId: '1:958810765713:web:00aadb6178c27b38540230',
    messagingSenderId: '958810765713',
    projectId: 'delivery-233fb',
    authDomain: 'delivery-233fb.firebaseapp.com',
    storageBucket: 'delivery-233fb.firebasestorage.app',
    measurementId: 'G-P4KGCK65LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLSAw2eaVlR72z7znhezSp5pfq9Tx4Rs',
    appId: '1:958810765713:android:f17777b19a93edc4540230',
    messagingSenderId: '958810765713',
    projectId: 'delivery-233fb',
    storageBucket: 'delivery-233fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBAPUHtyD9PFtNRg_lLCZPyAZJrG5XuTI',
    appId: '1:958810765713:ios:2d77822da7c1dd19540230',
    messagingSenderId: '958810765713',
    projectId: 'delivery-233fb',
    storageBucket: 'delivery-233fb.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );
}
