// Mocks generated by Mockito 5.4.6 from annotations
// in delivery_app/test/features/auth/domain/usecases/get_tokens_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:delivery_app/core/error/failures.dart' as _i5;
import 'package:delivery_app/features/auth/domain/entities/auth_entity.dart'
    as _i6;
import 'package:delivery_app/features/auth/domain/repositories/token_storage_repository.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TokenStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageRepository extends _i1.Mock
    implements _i2.TokenStorageRepository {
  MockTokenStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> storeTokens(
    _i6.AuthEntity? tokens,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeTokens, [tokens]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#storeTokens, [tokens]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.AuthEntity?>> getTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getTokens, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.AuthEntity?>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.AuthEntity?>>(
                    this,
                    Invocation.method(#getTokens, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.AuthEntity?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#clearTokens, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> hasTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasTokens, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
                this,
                Invocation.method(#hasTokens, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateAccessToken(
    String? accessToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccessToken, [accessToken]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateAccessToken, [accessToken]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
